name: tuwaiq_gallery_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

dependencies:
  aes256gcm: ^1.0.1
  args: ^2.4.0
  dotenv: ^4.2.0
  encrypt: ^5.0.3
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  supabase: ^2.2.7
  uuid: ^4.4.2

  #security
  shelf_helmet: ^2.3.0
  shelf_rate_limiter: ^1.0.1
  content_length_validator: ^1.2.1
  shelf_cors_headers: ^0.1.5
  chopper: ^8.0.0
  json_annotation: ^4.8.0



dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  shelf_hotreload: ^1.5.0
  test: ^1.24.0
  build_runner: ^2.3.3
  chopper_generator: ^8.0.0
  json_serializable: ^6.6.1
